services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock



  gregorian-api:
    image: guiflauzino18/gregorian-api:latest
    labels:
      - "traefik.http.routers.gregorian-api.rule=Host(`api.gregorian.com`)" #Traefik usa para saber qual fqdn rotear para o container
      - "traefik.http.services.gregorian-api.loadbalancer.server.port=8080"  #Roteia para a porta 8080

    environment:
      - MYSQL_IP=mysql
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - JWT_SECRET=$JWT_SECRET



  gregorian-app:
    image: guiflauzino18/gregorian-app:beta
    labels:
      - "traefik.http.routers.gregorian-app.rule=Host(`cliente.gregorian.com`)"

    environment:
      - API_URL=http://api.gregorian.com


  mysql:
    image: mysql:8.0-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=gregorian
      - MYSQL_USER=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
